openapi: 3.0.3

info:
  title: Accounts schemas
  version: '1.0'

paths:
  /accounts:
    post:
      summary: Create a new Account
      description: Create a new Account for an existing Saver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: The Account has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
      tags:
        - Accounts

components:
  schemas:
    Account:
      type: object
      properties:
        saverId:
          type: string
          example: 668286d72ea20e3725f813eb
          description: The ID of the Saver that owns the Account
        sourceAccountDetails:
          type: object
          properties:
            accountNumber:
              type: string
              example: 11223344
              description: The bank account number of the Saver
            sortCode:
              type: string
              example: 60-83-71
              description: The sort code of the Saver
            accountOwner:
              type: string
              example: Christopher Robin
              description: The name on the Saver's bank account
          required:
            - accountNumber
            - sortCode
            - accountOwner
      required:
        - saverId
        - sourceAccountDetails
            