openapi: 3.0.3

info:
  title: Accounts schemas
  version: '1.0'

paths:
  /accounts:
    post:
      summary: Create a new Account
      description: Create a new Account for an existing Saver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: The Account has been created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
      tags:
        - Accounts

components:
  schemas:
    Account:
      type: object
      properties:
        saverId:
          type: string
          example: 668286d72ea20e3725f813eb
          description: The ID of the Saver that owns the Account
        name:
          type: string
          example: Holiday in Bahamas
          description: A friendly name that a Saver can use to identify the Account
        goalAmount:
          type: number
          multipleOf: 0.01
          example: 12345.67
          description: The amount the Saver wants to save for their goal
        isoCurrencyCode:
          type: string
          enum: ['GBP']
          description: The currency of the account in ISO 4217 format.
        sourceAccountDetails:
          type: object
          description: This bank account is where Withdrawal Transactions will be paid to
          properties:
            accountNumber:
              type: string
              example: '11223344'
              description: The bank account number of the Saver
            sortCode:
              type: string
              example: 60-83-71
              description: The sort code of the Saver's bank account
            accountOwner:
              type: string
              example: Christopher Robin
              description: The name on the Saver's bank account
          required:
            - accountNumber
            - sortCode
            - accountOwner
      required:
        - saverId
        - name
        - goalAmount
        - sourceAccountDetails
            