openapi: 3.0.3
info:
  title: Sync Savings API Specification
  version: '1.0'
  x-logo:
    url: ./sync_star.png
    backgroundColor: '#FFFFFF'
  description: |
    # Introduction

    Welcome to the Sync Savings API, providing access to the Sync Savings Platform.

    ℹ️ Embedded savings is the integration of cash savings products into other digital applications without the need to redirect users to the underlying financial institution. Embedded financial services enable providers to offer seamless access to relevant financial products at the point of intent, and thus drive engagement and value to customers.

    🔑 Authentication: The API requires authentication using API keys included in request headers (see authorize)

    Should you have any queries on the standards implemented or the capability of our services, please do let us know by emailing us at **contact@sync-savings.com**

    # Overview

    The Sync Savings API provides a set of RESTful, JSON-based APIs that can be used to create and manage savings for your users.

    <Insert generalised workflow here>

    # Security

    We store only the required information to be able to provide your users with a savings account, all data is encrypted at rest and in transit by TLS 1.2+. Authentication is provided by AWS's Cognito product which restricts access to the API.
    
    User data is segregated by Distributor so that it is only accessible to clients from the relevant Distributor and with a token bearing the correct level of permission.

servers:
  - url: https://api.staging.sync-savings.com
    description: Staging API
  - url: https://api.sync-savings.com
    description: Production API (uses live data)

security:
  - oauth2: []

tags:
  - name: Savers
    description: |
      Savers are Distributors' customers, Savers want to open an Account to save money.

  - name: Accounts
    description: |
      Accounts are owned by a Saver, they are the representation in Sync's system of the Saver's bank account.

  - name: Transactions
    description: |
      Transactions are owned by an Account, they are the representation in Sync's system of cash movements in the Saver's bank account.

paths:
  /savers:
    $ref: 'savers.yaml#/paths/~1savers'
  /savers/{saverId}:
    $ref: 'savers.yaml#/paths/~1savers~1{saverId}'
  /accounts:
    $ref: 'accounts.yaml#/paths/~1accounts'
  /accounts/{accountId}:
    $ref: 'accounts.yaml#/paths/~1accounts~1{accountId}'
  /transactions:
    $ref: 'transactions.yaml#/paths/~1transactions'
  /transactions/{transactionId}:
    $ref: 'transactions.yaml#/paths/~1transactions~1{transactionId}'

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          scopes: {}